# Netlify Configuration for AI Panel of Experts
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command - empty for static sites
  command = ""
  
  # Directory to publish - root directory
  publish = "."
  
  # Build environment
  [build.environment]
    NODE_VERSION = "18"
    HUGO_VERSION = "0.110.0"

# Production context (main branch)
[context.production]
  command = "echo 'Production deployment - static site'"
  
[context.production.environment]
  NODE_ENV = "production"

# Deploy preview context (pull requests)
[context.deploy-preview]
  command = "echo 'Deploy preview - static site'"

# Branch deploy context (other branches)
[context.branch-deploy]
  command = "echo 'Branch deployment - static site'"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # CORS headers for API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    
    # Cache control
    Cache-Control = "public, max-age=31536000"

# Specific headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Specific headers for CSS and JS files
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA-like behavior (if needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 404 handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Environment variables (these are examples, not actual secrets)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugins (optional - for future enhancements)
[[plugins]]
  package = "netlify-plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Form handling (if adding contact forms later)
[build.processing.skip_processing] = false

# Split testing (for A/B testing)
[context.production.environment]
  ENABLE_SPLIT_TESTING = "false"

# Dev settings
[dev]
  command = "python -m http.server 8000"
  port = 8000
  targetPort = 8000
  publish = "."
  autoLaunch = true

# Edge functions (for future serverless features)
[build.edge_functions]
  directory = "netlify/edge-functions"

# Large Media (if adding large assets)
[lfs]
  gitlfs = false 
